### ISSUE TITLE
算力 BUG

### ISSUE THREAD

**Issue by iiinnn** [allenlinkme/hookpool_client_chia#89]
只开钱包和2.9.1挖矿软件，11T的P文件，开了一晚上贡献值只有0.001，没有任何收入！

**Comment by iiinnn** [comment]
这下贡献值直接为 0 了，怎么回事啊？

**Comment by iiinnn** [comment]
2021-06-09T22:03:47.392 harvester chia.harvester.harvester: WARNING  收到 farmer的info
2021-06-09T22:03:47.396 harvester harvester_server        : ERROR    Exception: unsupported operand type(s) for +: 'int' and 'str', {'host': '120.24.31.67', 'port': 8443}. Traceback (most recent call last):
  File "chia\server\server.py", line 578, in chia.server.server.ChiaServer.incoming_api_task.api_call.wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 123, in get_farm_info
  File "chia\harvester\harvester.py", line 198, in send_farm_msg
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2021-06-09T22:03:47.398 harvester harvester_server        : ERROR    Exception: unsupported operand type(s) for +: 'int' and 'str' <class 'TypeError'>, closing connection {'host': '120.24.31.67', 'port': 8443}. Traceback (most recent call last):
  File "chia\server\server.py", line 588, in chia.server.server.ChiaServer.incoming_api_task.api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 585, in wrapped_coroutine
  File "chia\server\server.py", line 578, in chia.server.server.ChiaServer.incoming_api_task.api_call.wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 123, in get_farm_info
  File "chia\harvester\harvester.py", line 198, in send_farm_msg
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2021-06-09T22:03:47.425 harvester harvester_server        : WARNING  Banning 120.24.31.67 for 10 seconds
2021-06-09T22:04:55.319 harvester harvester               : WARNING  Reconnecting to peer {'host': '120.24.31.67', 'port': 8443}
2021-06-09T22:04:56.689 harvester harvester_server        : ERROR    Exception: unsupported operand type(s) for +: 'int' and 'str', {'host': '120.24.31.67', 'port': 8443}. Traceback (most recent call last):
  File "chia\server\server.py", line 578, in chia.server.server.ChiaServer.incoming_api_task.api_call.wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 83, in harvester_handshake
  File "chia\harvester\harvester.py", line 174, in refresh_plots
  File "chia\harvester\harvester.py", line 198, in send_farm_msg
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2021-06-09T22:04:56.701 harvester harvester_server        : ERROR    Exception: unsupported operand type(s) for +: 'int' and 'str' <class 'TypeError'>, closing connection {'host': '120.24.31.67', 'port': 8443}. Traceback (most recent call last):
  File "chia\server\server.py", line 588, in chia.server.server.ChiaServer.incoming_api_task.api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 585, in wrapped_coroutine
  File "chia\server\server.py", line 578, in chia.server.server.ChiaServer.incoming_api_task.api_call.wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 83, in harvester_handshake
  File "chia\harvester\harvester.py", line 174, in refresh_plots
  File "chia\harvester\harvester.py", line 198, in send_farm_msg
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2021-06-09T22:04:56.739 harvester harvester_server        : WARNING  Banning 120.24.31.67 for 10 seconds
2021-06-09T22:05:04.496 harvester harvester               : WARNING  Reconnecting to peer {'host': '120.24.31.67', 'port': 8443}
2021-06-09T22:05:04.497 harvester harvester_server        : WARNING  Peer 120.24.31.67 is still banned, not connecting to it
2021-06-09T22:05:13.516 harvester harvester               : WARNING  Reconnecting to peer {'host': '120.24.31.67', 'port': 8443}
2021-06-09T22:05:13.648 harvester asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<<coroutine without __name__>()> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-09T22:05:13.701 harvester chia.harvester.harvester: WARNING  start mining
